cmake_minimum_required(VERSION 3.0)

set(MY_ADDITIONAL_SOURCES
    # Please add your source files here
    core/color.cpp
    core/point.cpp
    core/vector.cpp
    rt/cameras/orthographic.cpp
    rt/cameras/perspective.cpp
    rt/ray.cpp
    rt/renderer.cpp
    ##################
    rt/groups/simplegroup.cpp
    rt/integrators/casting.cpp
    rt/integrators/castingdist.cpp
    rt/solids/solid.cpp
    rt/solids/aabox.cpp
    rt/solids/disc.cpp
    rt/solids/infiniteplane.cpp
    rt/solids/quad.cpp
    rt/solids/sphere.cpp
    rt/solids/triangle.cpp
    rt/intersection.cpp
    rt/bbox.cpp
)

set(ASSIGNMENT_SOURCES
    core/assert.h
    core/color.h
    core/image.cpp
    core/image.h
    core/julia.cpp
    core/julia.h
    core/macros.h
    core/point.h
    core/scalar.cpp
    core/scalar.h
    core/vector.h
    core/float4.h
    rt/cameras/camera.h
    rt/cameras/orthographic.h
    rt/cameras/perspective.h
    rt/ray.h
    rt/renderer.h
    ${MY_ADDITIONAL_SOURCES}
	main/a_julia.cpp
	main/a_cameras.cpp
    ###########################
    rt/groups/group.h
    rt/groups/simplegroup.h
    rt/integrators/integrator.h
    rt/integrators/casting.h
    rt/integrators/castingdist.h
    rt/solids/solid.h
    rt/solids/aabox.h
    rt/solids/disc.h
    rt/solids/infiniteplane.h
    rt/solids/quad.h
    rt/solids/sphere.h
    rt/solids/triangle.h
    rt/bbox.h
    rt/intersection.h
    rt/primitive.h
    rt/world.h
    #${MY_ADDITIONAL_SOURCES}
    main/a_solids.cpp
)
